### ISSUE TITLE
Add browser details

### ISSUE THREAD

**Issue by mukeshthawani** [anttiviljami/browser-autofill-phishing#1]
Hey, great demonstration. 

It would be better if you can add some browser-specific details.

>This is a simple demonstration of form fields hidden from the user, but will be filled anyways when using the browser form autofill feature, which poses a security risk for users, unaware of giving their information to the website.

In Safari, it will tell you what fields it will fill, you can also customise that. In Chrome that's not the case.

**Comment by Flimm** [comment]
Indeed. If this is an issue that only affects Chrome and Chromium, then it would be useful to be told that so that we can factor that into our decision when choosing a browser.

**Comment by anttiviljami** [comment]
Good point. Pull requests accepted! :)

**Comment by mukeshthawani** [comment]
Done.

**Comment by anttiviljami** [comment]
Thank you so much!
