### ISSUE TITLE
Style change on form items

### ISSUE THREAD

**Issue by digip** [anttiviljami/browser-autofill-phishing#2]
Cheers - DigiP

**Comment by anttiviljami** [comment]
Thanks for posting the issue. :)

This code really isn't intended for "practical use", so making it prettier isn't something I find terribly important here. I'm fully aware of better ways to hide the form fields, but here I've just opted for the easiest thing that came to my mind in 2 minutes.

Feel free to fork this repo and make your own, more user friendly example, though. Would be good to see some creative ways of hiding the fields, like invisible fonts or opacity changes e.g. :)

Appreciate the feedback!
