### ISSUE TITLE
Credit Card Numbers are vulnerable.

### ISSUE THREAD

**Issue by librien** [anttiviljami/browser-autofill-phishing#5]
Please see [arrju](https://www.reddit.com/user/arrju)'s jsfiddle [here](https://jsfiddle.net/okqks2cg/1/).

Credit card numbers are just as vulnerable as any.  

See [here](http://imgur.com/a/2XXB9).

This posts the following: 
```
"form": {
    "cardholder": "Fake Card", 
    "cc_cvv": "", 
    "cc_month": "11", 
    "cc_number": "123456789012345", 
    "cc_year": "2017"
  }, 
```

I guess that was to be expected, but I certainly think this should be included with the demo.

**Comment by spmedia** [comment]
Yes, please include CCs into this.

**Comment by Neo-Desktop** [comment]
@anttiviljami I've opened a PR to implement this. #6 should do so

**Comment by dandv** [comment]
If CCs are vulnerable, this should be mentioned in the README. The press picked this up but (unsurprisingly) referred in vague terms to whether CC #s are vulnerable or not.
